main: com.teunjojo.SimpleAutoRestart
name: ${project.name}
version: ${project.version}
description: ${project.description}
api-version: 1.13
author: teunjojo
website: ${project.url}
folia-supported: true
commands:
  simpleautorestart:
    description: Main SimpleAutoRestart command
    aliases: [sar, autorestart]
    usage: "Usage: /<command> [cancel | resume | status | set <hours>:<minutes>]"
    default: op